# Generated by Django 5.2.1 on 2025-05-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_options_alter_exchangeproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у'), ('damaged', 'Поврежденное')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
