# Generated by Django 5.2.1 on 2025-05-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_options_alter_exchangeproposal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category', 'condition'], name='ads_ad_categor_bb3ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['created_at'], name='ads_ad_created_9f5b83_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeproposal',
            index=models.Index(fields=['status', 'created_at'], name='ads_exchang_status_23a252_idx'),
        ),
    ]
